import { createSignal } from "solid-js";
import type { Meta, StoryObj } from "storybook-solidjs-vite";
import {
    BranchCommitGitDialog,
    CommitStagedGitDialog,
    DiscardFileGitDialog,
    DiscardUnstagedGitDialog,
    GitActionDialog,
} from "./git-review-dialogs";

const meta = {
    title: "Modals/GitReviewDialogs",
    parameters: { layout: "fullscreen" },
    tags: ["autodocs"],
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

export const ActionShell: Story = {
    render: () => (
        <GitActionDialog
            open
            title="Confirm action"
            pending={false}
            error=""
            confirmLabel="Confirm"
            onClose={() => {}}
            onConfirm={() => {}}
        >
            <p class="mb-4 text-sm text-slate-400">
                The shared shell for git review dialogs. It provides the
                overlay, escape/enter keys, error banner and button row.
            </p>
        </GitActionDialog>
    ),
};

export const ActionShellPending: Story = {
    render: () => (
        <GitActionDialog
            open
            title="Confirm action"
            pending
            error=""
            confirmLabel="Confirm"
            onClose={() => {}}
            onConfirm={() => {}}
        >
            <p class="mb-4 text-sm text-slate-400">
                Buttons disable while the action is in flight; the confirm
                button shows a spinner.
            </p>
        </GitActionDialog>
    ),
};

export const DiscardFile: Story = {
    render: () => (
        <DiscardFileGitDialog
            open
            filePath="internal/v2/app/project.go"
            pending={false}
            error=""
            onClose={() => {}}
            onConfirm={() => {}}
        />
    ),
};

export const DiscardFileWithError: Story = {
    render: () => (
        <DiscardFileGitDialog
            open
            filePath="internal/v2/app/project.go"
            pending={false}
            error="git: working tree has unmerged paths"
            onClose={() => {}}
            onConfirm={() => {}}
        />
    ),
};

export const DiscardUnstaged: Story = {
    render: () => (
        <DiscardUnstagedGitDialog
            open
            pending={false}
            error=""
            onClose={() => {}}
            onConfirm={() => {}}
        />
    ),
};

export const CommitStaged: Story = {
    render: () => {
        const [msg, setMsg] = createSignal(
            "feat(review): port collapsible section to components package",
        );
        return (
            <CommitStagedGitDialog
                open
                message={msg()}
                onMessage={setMsg}
                pending={false}
                error=""
                onClose={() => {}}
                onConfirm={() => {}}
            />
        );
    },
};

export const CommitStagedWithGenerate: Story = {
    render: () => {
        const [msg, setMsg] = createSignal("");
        return (
            <CommitStagedGitDialog
                open
                message={msg()}
                onMessage={setMsg}
                pending={false}
                error=""
                onClose={() => {}}
                onConfirm={() => {}}
                onGenerate={async () => {
                    await new Promise((r) => setTimeout(r, 600));
                    return "feat(review): port collapsible section to components package\n\nGenerated by AI from staged diff.";
                }}
            />
        );
    },
};

export const BranchAndCommit: Story = {
    render: () => {
        const [branch, setBranch] = createSignal("feature/port-review");
        const [msg, setMsg] = createSignal(
            "feat(review): port collapsible section to components package",
        );
        return (
            <BranchCommitGitDialog
                open
                branchName={branch()}
                commitMessage={msg()}
                onBranchName={setBranch}
                onCommitMessage={setMsg}
                pending={false}
                error=""
                onClose={() => {}}
                onConfirm={() => {}}
            />
        );
    },
};

export const BranchAndCommitPending: Story = {
    render: () => (
        <BranchCommitGitDialog
            open
            branchName="feature/port-review"
            commitMessage="feat(review): port collapsible section to components package"
            onBranchName={() => {}}
            onCommitMessage={() => {}}
            pending
            error=""
            onClose={() => {}}
            onConfirm={() => {}}
        />
    ),
};
