// Code generated by "sash bind"; DO NOT EDIT.

export interface SashBindingsConfig {
  apiBase?: string;
}

export interface SashFetchOpts {
  signal?: AbortSignal;
}

export function configureSashBindings(c: SashBindingsConfig): void;
export const devApiBaseURL: string;

export function eventsURL(): string;

export const API: {
  CreateThread(a0: string, a1: string, fetchOpts?: SashFetchOpts): Promise<object | null>;
  CreateWorkspaceFromFolder(a0: string, a1: string, fetchOpts?: SashFetchOpts): Promise<object | null>;
  CreateWorkspaceFromGit(a0: string, a1: string, fetchOpts?: SashFetchOpts): Promise<object | null>;
  GetGlobalSettings(fetchOpts?: SashFetchOpts): Promise<object | null>;
  GetThread(a0: string, fetchOpts?: SashFetchOpts): Promise<object | null>;
  GetWorkspace(a0: string, fetchOpts?: SashFetchOpts): Promise<object | null>;
  ListThreads(fetchOpts?: SashFetchOpts): Promise<(object | null)[]>;
  ListThreadsByWorkspace(a0: string, fetchOpts?: SashFetchOpts): Promise<(object | null)[]>;
  ListWorkspaces(fetchOpts?: SashFetchOpts): Promise<(object | null)[]>;
  RenameThread(a0: string, a1: string, fetchOpts?: SashFetchOpts): Promise<void>;
  SaveGlobalSettings(a0: object | null, fetchOpts?: SashFetchOpts): Promise<void>;
  SelectWorkspaceFolder(fetchOpts?: SashFetchOpts): Promise<string>;
  UpdateWorkspaceDetails(a0: string, a1: string, a2: string, fetchOpts?: SashFetchOpts): Promise<void>;
};

export interface SashSSESessionOpts {
  url?: string;
}

export interface SashSSESession {
  readonly source: EventSource;
  listenJSON<E extends string, T>(event: E, handler: (payload: T, ev: MessageEvent) => void): () => void;
  close(): void;
}

export function createSashSSESession(opts?: SashSSESessionOpts): SashSSESession;
