// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function CancelCreateProject():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearOpenRouterAPIKey():Promise<void>;

export function ConnectOpenRouterOAuth():Promise<void>;

export function CreateProjectFromFolder(arg1:string,arg2:string,arg3:string):Promise<store.Project>;

export function CreateProjectFromRemote(arg1:string,arg2:string):Promise<store.Project>;

export function CreateThread(arg1:string,arg2:boolean):Promise<store.Thread>;

export function DeleteProject(arg1:string,arg2:boolean):Promise<void>;

export function DeleteThread(arg1:string,arg2:boolean):Promise<void>;

export function DownloadLogs():Promise<void>;

export function ForkThreadAtMessage(arg1:string,arg2:string):Promise<store.Thread>;

export function GetBuildLabel():Promise<string>;

export function GetClaudeCLIInfo():Promise<store.ClaudeCLIInfo>;

export function GetCursorCLIInfo():Promise<store.CursorCLIInfo>;

export function GetFileDiff(arg1:string,arg2:string,arg3:string):Promise<store.FileDiff>;

export function GetOpenRouterUsageMetrics():Promise<store.OpenRouterUsageMetrics>;

export function GetProject(arg1:string):Promise<store.Project>;

export function GetSettings():Promise<store.Settings>;

export function GetThread(arg1:string):Promise<store.Thread>;

export function GetThreadGitReview(arg1:string):Promise<store.GitReview>;

export function GetThreadGitStatus(arg1:string):Promise<store.GitStatus>;

export function GitCheckoutNewBranchAndCommit(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitConflictState(arg1:string):Promise<store.GitConflictState>;

export function GitDiscardFile(arg1:string,arg2:string):Promise<void>;

export function GitDiscardUnstaged(arg1:string):Promise<void>;

export function GitFetch(arg1:string):Promise<void>;

export function GitListBranches(arg1:string):Promise<Array<string>>;

export function GitMerge(arg1:string,arg2:string):Promise<string>;

export function GitMergeContinue(arg1:string):Promise<string>;

export function GitPull(arg1:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitRebaseAbort(arg1:string):Promise<void>;

export function GitRebaseContinue(arg1:string):Promise<string>;

export function GitRebaseOnto(arg1:string,arg2:string):Promise<string>;

export function GitRenameBranch(arg1:string,arg2:string):Promise<void>;

export function GitStageFile(arg1:string,arg2:string):Promise<void>;

export function GitStageUnstaged(arg1:string):Promise<void>;

export function GitStageUntracked(arg1:string):Promise<void>;

export function GitStash(arg1:string):Promise<void>;

export function GitStashPop(arg1:string):Promise<void>;

export function GitUnstageAll(arg1:string):Promise<void>;

export function GitUnstageFile(arg1:string,arg2:string):Promise<void>;

export function IsPushAvailable():Promise<boolean>;

export function ListClaudeChatModels():Promise<Array<store.OpenRouterChatModel>>;

export function ListCursorChatModels():Promise<Array<store.OpenRouterChatModel>>;

export function ListLaneMessages(arg1:string,arg2:string):Promise<Array<store.ChatMessage>>;

export function ListLogs():Promise<Array<store.LogLine>>;

export function ListOpenRouterChatModels():Promise<Array<store.OpenRouterChatModel>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListThreadMessages(arg1:string):Promise<Array<store.ChatMessage>>;

export function ListThreads():Promise<Array<store.Thread>>;

export function RenameThread(arg1:string,arg2:string):Promise<void>;

export function ResolveGitConflictsWithUtilityAgent(arg1:string):Promise<string>;

export function ReviewBranchDiff(arg1:string):Promise<string>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function SelectProjectFolder():Promise<string>;

export function SendLaneMessage(arg1:string,arg2:string,arg3:string):Promise<store.ChatMessage>;

export function SendThreadMessage(arg1:string,arg2:string):Promise<Array<store.ChatMessage>>;

export function SetLogStreaming(arg1:boolean):Promise<void>;

export function SetThreadChatModel(arg1:string,arg2:string):Promise<void>;

export function SetThreadChatProvider(arg1:string,arg2:string):Promise<void>;

export function StreamResolveGitConflictsWithUtilityAgent(arg1:string):Promise<void>;

export function StreamReviewBranchDiff(arg1:string):Promise<void>;

export function SuggestCommitMessage(arg1:string):Promise<string>;

export function TerminalWebSocketURL():Promise<string>;

export function UpdateProject(arg1:store.Project):Promise<void>;
