// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {logstream} from '../models';

export function CancelCreateProject():Promise<void>;

export function CreateProjectFromFolder(arg1:string,arg2:string):Promise<store.Project>;

export function CreateProjectFromRemote(arg1:string,arg2:string):Promise<store.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<store.Project>;

export function ListProjects():Promise<Array<store.Project>>;

export function LogSnapshot():Promise<Array<logstream.LogLine>>;

export function SelectProjectFolder():Promise<string>;

export function SetLogStreaming(arg1:boolean):Promise<void>;

export function UpdateProject(arg1:store.Project):Promise<void>;
