// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCreateProject() {
  return window['go']['app']['App']['CancelCreateProject']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CreateProjectFromFolder(arg1, arg2) {
  return window['go']['app']['App']['CreateProjectFromFolder'](arg1, arg2);
}

export function CreateProjectFromRemote(arg1, arg2) {
  return window['go']['app']['App']['CreateProjectFromRemote'](arg1, arg2);
}

export function CreateThread(arg1) {
  return window['go']['app']['App']['CreateThread'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DownloadLogs() {
  return window['go']['app']['App']['DownloadLogs']();
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetThread(arg1) {
  return window['go']['app']['App']['GetThread'](arg1);
}

export function GetThreadGitReview(arg1) {
  return window['go']['app']['App']['GetThreadGitReview'](arg1);
}

export function GetThreadGitStatus(arg1) {
  return window['go']['app']['App']['GetThreadGitStatus'](arg1);
}

export function ListLogs() {
  return window['go']['app']['App']['ListLogs']();
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListThreadMessages(arg1) {
  return window['go']['app']['App']['ListThreadMessages'](arg1);
}

export function ListThreads() {
  return window['go']['app']['App']['ListThreads']();
}

export function SelectProjectFolder() {
  return window['go']['app']['App']['SelectProjectFolder']();
}

export function SendThreadMessage(arg1, arg2) {
  return window['go']['app']['App']['SendThreadMessage'](arg1, arg2);
}

export function SetLogStreaming(arg1) {
  return window['go']['app']['App']['SetLogStreaming'](arg1);
}

export function TerminalWebSocketURL() {
  return window['go']['app']['App']['TerminalWebSocketURL']();
}

export function UpdateProject(arg1) {
  return window['go']['app']['App']['UpdateProject'](arg1);
}
