// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCreateProject() {
  return window['go']['app']['App']['CancelCreateProject']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function ClearOpenRouterAPIKey() {
  return window['go']['app']['App']['ClearOpenRouterAPIKey']();
}

export function ConnectOpenRouterOAuth() {
  return window['go']['app']['App']['ConnectOpenRouterOAuth']();
}

export function CreateProjectFromFolder(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateProjectFromFolder'](arg1, arg2, arg3);
}

export function CreateProjectFromRemote(arg1, arg2) {
  return window['go']['app']['App']['CreateProjectFromRemote'](arg1, arg2);
}

export function CreateThread(arg1, arg2) {
  return window['go']['app']['App']['CreateThread'](arg1, arg2);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['app']['App']['DeleteProject'](arg1, arg2);
}

export function DeleteThread(arg1, arg2) {
  return window['go']['app']['App']['DeleteThread'](arg1, arg2);
}

export function DownloadLogs() {
  return window['go']['app']['App']['DownloadLogs']();
}

export function ForkThreadAtMessage(arg1, arg2) {
  return window['go']['app']['App']['ForkThreadAtMessage'](arg1, arg2);
}

export function GetBuildLabel() {
  return window['go']['app']['App']['GetBuildLabel']();
}

export function GetClaudeCLIInfo() {
  return window['go']['app']['App']['GetClaudeCLIInfo']();
}

export function GetCursorCLIInfo() {
  return window['go']['app']['App']['GetCursorCLIInfo']();
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetOpenRouterUsageMetrics() {
  return window['go']['app']['App']['GetOpenRouterUsageMetrics']();
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetThread(arg1) {
  return window['go']['app']['App']['GetThread'](arg1);
}

export function GetThreadGitReview(arg1) {
  return window['go']['app']['App']['GetThreadGitReview'](arg1);
}

export function GetThreadGitStatus(arg1) {
  return window['go']['app']['App']['GetThreadGitStatus'](arg1);
}

export function GitCheckoutNewBranchAndCommit(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitCheckoutNewBranchAndCommit'](arg1, arg2, arg3);
}

export function GitCommit(arg1, arg2) {
  return window['go']['app']['App']['GitCommit'](arg1, arg2);
}

export function GitConflictState(arg1) {
  return window['go']['app']['App']['GitConflictState'](arg1);
}

export function GitDiscardFile(arg1, arg2) {
  return window['go']['app']['App']['GitDiscardFile'](arg1, arg2);
}

export function GitDiscardUnstaged(arg1) {
  return window['go']['app']['App']['GitDiscardUnstaged'](arg1);
}

export function GitFetch(arg1) {
  return window['go']['app']['App']['GitFetch'](arg1);
}

export function GitListBranches(arg1) {
  return window['go']['app']['App']['GitListBranches'](arg1);
}

export function GitMerge(arg1, arg2) {
  return window['go']['app']['App']['GitMerge'](arg1, arg2);
}

export function GitMergeContinue(arg1) {
  return window['go']['app']['App']['GitMergeContinue'](arg1);
}

export function GitPull(arg1) {
  return window['go']['app']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['app']['App']['GitPush'](arg1);
}

export function GitRebaseAbort(arg1) {
  return window['go']['app']['App']['GitRebaseAbort'](arg1);
}

export function GitRebaseContinue(arg1) {
  return window['go']['app']['App']['GitRebaseContinue'](arg1);
}

export function GitRebaseOnto(arg1, arg2) {
  return window['go']['app']['App']['GitRebaseOnto'](arg1, arg2);
}

export function GitRenameBranch(arg1, arg2) {
  return window['go']['app']['App']['GitRenameBranch'](arg1, arg2);
}

export function GitStageFile(arg1, arg2) {
  return window['go']['app']['App']['GitStageFile'](arg1, arg2);
}

export function GitStageUnstaged(arg1) {
  return window['go']['app']['App']['GitStageUnstaged'](arg1);
}

export function GitStageUntracked(arg1) {
  return window['go']['app']['App']['GitStageUntracked'](arg1);
}

export function GitStash(arg1) {
  return window['go']['app']['App']['GitStash'](arg1);
}

export function GitStashPop(arg1) {
  return window['go']['app']['App']['GitStashPop'](arg1);
}

export function GitUnstageAll(arg1) {
  return window['go']['app']['App']['GitUnstageAll'](arg1);
}

export function GitUnstageFile(arg1, arg2) {
  return window['go']['app']['App']['GitUnstageFile'](arg1, arg2);
}

export function IsPushAvailable() {
  return window['go']['app']['App']['IsPushAvailable']();
}

export function ListClaudeChatModels() {
  return window['go']['app']['App']['ListClaudeChatModels']();
}

export function ListCursorChatModels() {
  return window['go']['app']['App']['ListCursorChatModels']();
}

export function ListLaneMessages(arg1, arg2) {
  return window['go']['app']['App']['ListLaneMessages'](arg1, arg2);
}

export function ListLogs() {
  return window['go']['app']['App']['ListLogs']();
}

export function ListOpenRouterChatModels() {
  return window['go']['app']['App']['ListOpenRouterChatModels']();
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListThreadMessages(arg1) {
  return window['go']['app']['App']['ListThreadMessages'](arg1);
}

export function ListThreads() {
  return window['go']['app']['App']['ListThreads']();
}

export function RenameThread(arg1, arg2) {
  return window['go']['app']['App']['RenameThread'](arg1, arg2);
}

export function ResolveGitConflictsWithUtilityAgent(arg1) {
  return window['go']['app']['App']['ResolveGitConflictsWithUtilityAgent'](arg1);
}

export function ReviewBranchDiff(arg1) {
  return window['go']['app']['App']['ReviewBranchDiff'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SelectProjectFolder() {
  return window['go']['app']['App']['SelectProjectFolder']();
}

export function SendLaneMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendLaneMessage'](arg1, arg2, arg3);
}

export function SendThreadMessage(arg1, arg2) {
  return window['go']['app']['App']['SendThreadMessage'](arg1, arg2);
}

export function SetLogStreaming(arg1) {
  return window['go']['app']['App']['SetLogStreaming'](arg1);
}

export function SetThreadChatModel(arg1, arg2) {
  return window['go']['app']['App']['SetThreadChatModel'](arg1, arg2);
}

export function SetThreadChatProvider(arg1, arg2) {
  return window['go']['app']['App']['SetThreadChatProvider'](arg1, arg2);
}

export function StreamReviewBranchDiff(arg1) {
  return window['go']['app']['App']['StreamReviewBranchDiff'](arg1);
}

export function SuggestCommitMessage(arg1) {
  return window['go']['app']['App']['SuggestCommitMessage'](arg1);
}

export function TerminalWebSocketURL() {
  return window['go']['app']['App']['TerminalWebSocketURL']();
}

export function UpdateProject(arg1) {
  return window['go']['app']['App']['UpdateProject'](arg1);
}
