// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['app']['Project']['Get'](arg1);
}

export function List() {
  return window['go']['app']['Project']['List']();
}
