// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Get(arg1:string):Promise<store.Project>;

export function List():Promise<Array<store.Project>>;
