// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspaceFromFolder(arg1, arg2) {
  return window['go']['app']['Project']['CreateWorkspaceFromFolder'](arg1, arg2);
}

export function CreateWorkspaceFromGit(arg1, arg2) {
  return window['go']['app']['Project']['CreateWorkspaceFromGit'](arg1, arg2);
}

export function Get(arg1) {
  return window['go']['app']['Project']['Get'](arg1);
}

export function List() {
  return window['go']['app']['Project']['List']();
}

export function SelectWorkspaceFolder() {
  return window['go']['app']['Project']['SelectWorkspaceFolder']();
}

export function SetContext(arg1) {
  return window['go']['app']['Project']['SetContext'](arg1);
}
