// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobal() {
  return window['go']['app']['Settings']['GetGlobal']();
}

export function SaveGlobal(arg1) {
  return window['go']['app']['Settings']['SaveGlobal'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['Settings']['SetContext'](arg1);
}
