// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {context} from '../models';

export function GetGlobal():Promise<store.GlobalSettings>;

export function SaveGlobal(arg1:store.GlobalSettings):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
