// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {context} from '../models';

export function Create(arg1:string,arg2:string):Promise<store.Thread>;

export function Get(arg1:string):Promise<store.Thread>;

export function List():Promise<Array<store.Thread>>;

export function ListByProject(arg1:string):Promise<Array<store.Thread>>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
