// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['app']['Thread']['Create'](arg1, arg2);
}

export function Get(arg1) {
  return window['go']['app']['Thread']['Get'](arg1);
}

export function List() {
  return window['go']['app']['Thread']['List']();
}

export function ListByProject(arg1) {
  return window['go']['app']['Thread']['ListByProject'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['app']['Thread']['Rename'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['app']['Thread']['SetContext'](arg1);
}
