// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {context} from '../models';

export function CreateWorkspaceFromFolder(arg1:string,arg2:string):Promise<store.Workspace>;

export function CreateWorkspaceFromGit(arg1:string,arg2:string):Promise<store.Workspace>;

export function Get(arg1:string):Promise<store.Workspace>;

export function List():Promise<Array<store.Workspace>>;

export function SelectWorkspaceFolder():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateDetails(arg1:string,arg2:string,arg3:string):Promise<void>;
