// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspaceFromFolder(arg1, arg2) {
  return window['go']['app']['Workspace']['CreateWorkspaceFromFolder'](arg1, arg2);
}

export function CreateWorkspaceFromGit(arg1, arg2) {
  return window['go']['app']['Workspace']['CreateWorkspaceFromGit'](arg1, arg2);
}

export function Get(arg1) {
  return window['go']['app']['Workspace']['Get'](arg1);
}

export function List() {
  return window['go']['app']['Workspace']['List']();
}

export function SelectWorkspaceFolder() {
  return window['go']['app']['Workspace']['SelectWorkspaceFolder']();
}

export function SetContext(arg1) {
  return window['go']['app']['Workspace']['SetContext'](arg1);
}

export function UpdateDetails(arg1, arg2, arg3) {
  return window['go']['app']['Workspace']['UpdateDetails'](arg1, arg2, arg3);
}
