// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function CancelCreateProject():Promise<void>;

export function CreateProjectFromFolder(arg1:string,arg2:string):Promise<store.Project>;

export function CreateProjectFromRemote(arg1:string,arg2:string):Promise<store.Project>;

export function ListProjects():Promise<Array<store.Project>>;

export function SelectProjectFolder():Promise<string>;
